sqlite/sqliteDBDump.txt
beginning of restructuring for MoBI
=> update DB, WIP

preprocessing/preproc_groupPoints.R
Figuring out how to group observations. This is an initial foray. @ChristopherTracey @dnbucklin I think this would only apply to terrestrial so I'm suggesting it gets pulled only there. I know I'm going to get confused as to the best way to handle these three branches!
=> WIP grouping points

3_createModel.R, 4_predictModelToStudyArea.R, helper/run_SDM.R, sqlite/sqliteDBDump.sql
This adds a new column to tblModelResults to store the latest git commit hash value, pulled prior to running script 3.
Also removed a testing feature in script 4 (clipping the raster stack).
=> add last commit hash to tblModelResults$repo_head

3_createModel.R, 4_predictModelToStudyArea.R, helper/run_SDM.R, user_run_SDM.R
I think this captures all the HUC integration up to actually cropping rasters and running the predict. 
I also added some minor bug fixes to make the scripts work when using very few env vars during testing.
=> Accomodate different ranges

MetadataEval_knitr.rnw, sqlite/sqliteDBDump.sql
Some of these should have been made to the master--slowly learning...
=> aquatic updates

MetadataEval_knitr.rnw
references #54 
Adds a title and standard legend outside of the main mapping area, so it won't overlap data.
=> map title/legend standardizing

2_attributePoints.R, 3_createModel.R, 4_predictModelToStudyArea.R
accommodate long env var file names
=> Envvar long names

0_user_run_SDM.R, 2_attributePoints.R, 3_createModel.R, 4_predictModelToStudyArea.R, 5_createMetadata.r, helper/0_user_run_SDM_rerun.R
Removed remaining `rgdal` shapefile reading/writing in favor of `sf`; will merge same changes to master.
=> use sf in all scripts

2_attributePoints.R
nchar on line 30 won't work on factors ...
=> need strings not factors

0_user_run_SDM.R, 1_pointsInPolys_cleanBkgPts.R
this does not yet take care of shapefile export (https://github.com/HeritageNetwork/Regional_SDM/issues/69)  but does take care of https://github.com/HeritageNetwork/Regional_SDM/issues/72
=> carry over background sqlite info

0_user_run_SDM.R, 4c_additionalMetadataComments.r, 5_createMetadata.r, MetadataEval_knitr.rnw, helper/run_SDM.R
All credit of work to @ChristopherTracey.
=> incorporate metadata rubric

0_user_run_SDM.R, 4c_additionalMetadataComments.r, 5_createMetadata.r, MetadataEval_knitr.rnw, helper/run_SDM.R
get most recent edits into master
=> rubric for metadata

4_predictModelToStudyArea.R
.. so that there are no warnings if the `if` loop is never entered (the norm at the moment for me)
=> move rm call

MetadataEval_knitr.rnw
pushing to both terrestrial and master
=> some metadata updates

MetadataEval_knitr.rnw
https://github.com/HeritageNetwork/Regional_SDM/issues/88
=> fix funny line spacing in biblio

MetadataEval_knitr.rnw
=> more metadata fixes

1_pointsInPolys_cleanBkgPts.R, 3_createModel.R, 4b_thresholdModel.R
=> align input presence file schema better with aquatic. issue #14

1_pointsInPolys_cleanBkgPts.R
clean up background points handling.  Needed when background points are for entire CONUS
=> Terrestrial

MetadataEval_knitr.rnw
add recent metadata fixes by @ChristopherTracey   (thanks Chris).
=> add metadata fixes

sqlite/sqliteDBDump.sql
=> add seed column in sqlite

MetadataEval_knitr.rnw
As Bruce Young pointed out in chat on MoBI tech call
=> Fixed missing word in Figure 4 caption

3_createModel.R
addressing #118 , also move seed to above validation loop. @ChristopherTracey try this out.
=> threshold in validation loop (and move seed)

3_createModel.R
add MTP for validation threshold, fix bug in maxSSS validation threshold (but commented out right now).
=> add MTP for validation threshold, fix bug in maxSSS 

MetadataEval_knitr.rnw
=> clarity to thermometer wording

MetadataEval_knitr.rnw
(for now, 100km across), if smaller area depicted, expand. See #53
=> set map maximum scale

LICENSE.txt, MetadataEval_knitr.rnw, README.md
License added as first step for #110 
as described here: 
https://help.github.com/en/articles/referencing-and-citing-content
=> small metadata fixes, add license

LICENSE.txt, README.md
=> add creative commons license

4b_thresholdModel.R, preprocessing/preproc_attributeBackgroundPts.R, preprocessing/preproc_populate_lkpSpeciesTable.R
- in 4b, call list entries by name (#108)
- still work in progress (WIP) for attribute background points
- fix "SUB" (subterranean) attribution in new script to population lkpSpecies table
=> call list entries by name not number (and more)

MetadataEval_knitr.rnw, helper/crop_mask_rast.R
- set scale to minimum of 1:5,000,000
- study area: remove holes, clip to conus
=> metadata range map cleanups

helper/run_SDM.R
@ChristopherTracey   you need to apply this file name change for the wrapper to work. Sorry I missed it earlier.
=> fix file name change

2_attributePoints.R, MetadataEval_knitr.rnw
-- clear program name from metadata footer
-- set validation to MTP in metadata
-- refactor script 2
=> small fixes

0_user_run_SDM.R, 3_createModel.R, 4c_additMetadComments_rubricUpdate.r
when localitydata$status is NA, the if() statement fails. https://github.com/HeritageNetwork/Regional_SDM/commit/c02581fd463f9608c1480e03c3f641ab72fa1d4b replaces the NA with "in progress" so the if() statement can pass it by.
=> fix for tracking DB status

helper/crop_mask_rast.R
unintended consequence of clipping to national boundary: state boundaries need to get re-dissolved.
=> dissolve state bounds of clipped layer

postprocessing/exportForMapReviewTool.r
change from using reticulate package to arcgisbinding package
=> fix gdb part of map review tool

1_pointsInPolys_cleanBkgPts.R, 2_attributePoints.R, 4_predictModelToStudyArea.R, 5_createMetadata.r, postprocessing/exportForMapReviewTool.r
Changed the script to run for both terrestrial and aquatic branches using the `modType` value from the lkpSpecies layer.  It's not currently working for values of "Both", so we should look into options for that.
@tghoward, please check this out and let me know what you think.
=> Integrated Aquatic results into the review tool prepper

preprocessing/preproc_groupPoints.R
=> group points preprocessing

helper/crop_mask_rast.R
clipping fails if shape not valid
=> check if clip shape is valid

0_user_run_SDM.R, preprocessing/preproc_attributeBackgroundPts.R
clean up the preprocessing script for attributing background points. Plus script 0 coming along for the ride
=> preproc - attribute points

2_attributePoints.R, 3_createModel.R, helper/crop_mask_rast.R
First step for getting regional predictors integrated into modeling
=> bug fixes and regional predictors

2_attributePoints.R, 3_createModel.R
PR primarily for a raster naming bug that crops up with regional rasters. Also slight clean up of script 3.
=> raster naming bug

1_pointsInPolys_cleanBkgPts.R, 2_attributePoints.R, 3_createModel.R, 4_predictModelToStudyArea.R, helper/0_user_run_SDM_rerun.R, helper/crop_mask_rast.R, helper/run_SDM.R
We've been having problems with some of the parallel calls not running in parallel. Finally! tracked it down to the different environments confusing the packages. The changes in b99527a move *all* processing to the global environment (.GlobalEnvironment). This appears to fix our problems. 
The other commit (c8d419a) speeds up partial plot creation for the terrestrial branch, subsetting like in the aquatic branch, but subsetting by pres/abs group instead of overall.
=> fix environment problems

4c_additMetadComments_rubricUpdate.r
use SQL Server instead of Access DB. We can't seem to save connection pwds in ODBC setup so change system to no longer require a previously defined ODBC connection but use a local text file with connection information that does not sync up to github.
=> use mobi-tracker on SQL Server

4c_additMetadComments_rubricUpdate.r
whoops. clean up path to file with connection settings. Also need to move this to script 0, I suppose.
=> connection string path

helper/run_SDM.R
per issue discussed here: #181
=> check for GDAL, MiKTeX, and packages

helper/pkg_check.R, helper/run_SDM.R
merges got a little funky, but finally got the change in properly
=> add odbc to package check

0_user_run_SDM.R, 3_createModel.R, 4c_additMetadComments_rubricUpdate.r, helper/run_SDM.R
- also added a simple looping construct at the bottom of script0
- the odbc string (file) location should probably be defined in script0 as well ... TODO.
=> allow validation by polygon if <5 groups

3_createModel.R
=> move envvar_list subsetting so df.abs names are lowercase

postprocessing/exportForMapReviewTool.r
- At end of script, write up to mobi tracking DB:
- check modeled checkbox
- add in modeled comments model name and date like this: "calotibu_20190506_081539 prepped for review tool on 2019-05-07"
- also revert to maxSSS when MTPEO==1 (already had when MTPEO==0) for terrestrial. Need to find a way to find other cases where maxSSS should be used.
=> update tracking DB with model complete

postprocessing/exportForMapReviewTool.r
=> huc csv fix

postprocessing/exportForMapReviewTool.r
1. For terrestrial, change threshold so that prediction area is slightly higher for cases with high habitat specificity. 
2. Upload additional information to the tracking DB. I think I covered this pretty well for both terrestrial and aquatic.
=> mods for upload tool export

postprocessing/exportForMapReviewTool.r
There's now a parent table to the workflow table and reviewTool table called modelCycle that allows multiple modeling runs for each species, and separate tracking of those runs.  These changes should fix the exports to Mobi Tracker to account for this structure.
=> incorporate model_cycle for export to Tracker

4_predictModelToStudyArea.R, helper/crop_mask_rast.R, helper/pkg_check.R
gdalwarp was not snapping rasters correctly. This new method is still fast and correctly writes aligned rasters.
=> improve raster cropping for predict

0_user_run_SDM.R, 1_pointsInPolys_cleanBkgPts.R, 3_createModel.R, 4c_additMetadComments_rubricUpdate.r, 5_createMetadata.r
tweaks to handle software updates and a few fixes.
=> Get terr running

preprocessing/preproc_groupPoints.R
small updates to the preprocessing script for points and polys
=> point grouping to use geopkg, cleanup

2_attributePoints.R
Mostly Patrick McIntyre improvements to script 2
=> attribute by groups if needed

2_attributePoints.R
first attempt to use stars package to address better raster processing for large ranges/many points.
Could not combine all rasters into a single stars object, so currently reads each raster in as a stars object and uses st_extract within a loop.
no parallelization used but seems quite fast without
need to understand why some files cannot be combined in stars (e.g. clim_bio1 and beersx1000 -different crs?)
=> update to script 2_attributePoint.R with stars
